name: CI DEPLOY
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.3.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: |
        git config --global user.email "github-action@users.noreply.github.com"
        git config --global user.name "GitHub Action"
    - run: yarn install
    - run: yarn deploy
